spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSLDialect
  mail:
    host: localhost
    port: 1025
    username: aman
    password: aman
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimout: 50000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: B2CB35BC6238966B6F16271E6D463B2CB35BC6238966B6F16271E6D463
      expiration: 8640000